name: Create, publish container image

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: registry.dev.rafay-edge.net
  IMAGE_NAME: ${{ github.repository }}
  GOPRIVATE: https://github.com/RafaySystems

jobs:

  build-push:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.TOKEN }}:x-oauth-basic@github.com/RafaySystems".insteadOf "https://github.com/RafaySystems"

      - name: vendor packages
        run: go mod tidy && go mod vendor

      # Sanity check before publishing
      - name: Test all
        run: go test -v ./...

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
